souffle: souffle::AstPrimitiveType Class Reference
souffle::AstPrimitiveType Class Reference
A primitive type is named type that can either be a sub-type of the build-in number or symbol type.
#include <AstType.h>
Public Member Functions
AstPrimitiveType (const AstQualifiedName &name, TypeAttribute type)
Creates a new primitive type.
AstPrimitiveType * clone () const override
Create a clone (i.e.
bool isNumeric () const
Tests whether this type is a numeric type.
bool isSymbolic () const
Tests whether this type is a symbolic type.
Public Member Functions inherited from souffle::AstType
AstType (AstQualifiedName name={""})
const AstQualifiedName & getQualifiedName () const
get type name
void setQualifiedName (const AstQualifiedName &name)
set type name
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
TypeAttribute type
type attribute
Detailed Description
A primitive type is named type that can either be a sub-type of the build-in number or symbol type.
Primitive types are the most basic building blocks of souffle's type system.
Definition at line 61 of file AstType.h.
Constructor & Destructor Documentation
AstPrimitiveType()
souffle::AstPrimitiveType::AstPrimitiveType (const AstQualifiedName & name, TypeAttribute type) inline
Creates a new primitive type.
Definition at line 64 of file AstType.h.
 : AstType(name), type(type) {}
Member Function Documentation
clone()
AstPrimitiveType* souffle::AstPrimitiveType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstType.
Definition at line 76 of file AstType.h.
References souffle::AstType::getQualifiedName(), and souffle::AstNode::getSrcLoc().
{
         auto res = new AstPrimitiveType(getQualifiedName(), type);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
equal()
bool souffle::AstPrimitiveType::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 87 of file AstType.h.
References souffle::AstType::getQualifiedName().
{
         assert(nullptr != dynamic_cast<const AstPrimitiveType*>(&node));
         const auto& other = static_cast<const AstPrimitiveType&>(node);
         return getQualifiedName() == other.getQualifiedName() && type == other.type;
     }
isNumeric()
bool souffle::AstPrimitiveType::isNumeric () const inline
Tests whether this type is a numeric type.
Definition at line 67 of file AstType.h.
References souffle::isNumericType().
{
         return isNumericType(type);
     }
isSymbolic()
bool souffle::AstPrimitiveType::isSymbolic () const inline
Tests whether this type is a symbolic type.
Definition at line 72 of file AstType.h.
References souffle::Symbol.
{
         return type == TypeAttribute::Symbol;
     }
print()
void souffle::AstPrimitiveType::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 83 of file AstType.h.
References souffle::AstType::getQualifiedName(), and souffle::Signed.
{
         os << ".type " << getQualifiedName() << (type == TypeAttribute::Signed ? "= number" : "");
     }
Field Documentation
type
TypeAttribute souffle::AstPrimitiveType::type private
type attribute
Definition at line 95 of file AstType.h.
The documentation for this class was generated from the following file:
AstType.h