souffle: souffle::TypeEnvironment Class Reference
souffle::TypeEnvironment Class Reference
A type environment is a set of types.
#include <TypeSystem.h>
Public Member Functions
void clear ()
PrimitiveType & createFloatType (const AstQualifiedName &name)
PrimitiveType & createNumericType (const AstQualifiedName &name)
RecordType & createRecordType (const AstQualifiedName &name)
PrimitiveType & createSymbolType (const AstQualifiedName &name)
template<typename T , typename... Args>
T & createType (const AstQualifiedName &name, const Args &... args)
UnionType & createUnionType (const AstQualifiedName &name)
PrimitiveType & createUnsignedType (const AstQualifiedName &name)
TypeSet getAllTypes () const
const Type & getFloatType () const
Type * getModifiableType (const AstQualifiedName &name)
const Type & getNumberType () const
const Type & getSymbolType () const
const Type & getType (const AstQualifiedName &) const
const Type & getUnsignedType () const
bool isPredefinedType (const AstQualifiedName &identifier) const
bool isPredefinedType (const Type &typeName) const
bool isType (const AstQualifiedName &) const
bool isType (const Type &type) const
TypeSet predefinedTypes () const
void print (std::ostream &out) const
void swap (TypeEnvironment &env)
TypeEnvironment ()
TypeEnvironment (const TypeEnvironment &)=delete
~TypeEnvironment ()
Private Member Functions
void addType (Type &type)
Register types created by one of the factory functions.
Private Attributes
std::map< AstQualifiedName, Type * > types
The list of covered types.
Friends
std::ostream & operator<< (std::ostream &out, const TypeEnvironment &environment)
Detailed Description
A type environment is a set of types.
It's main purpose is to provide an enumeration of all all types within a given program. Additionally, it manages the life cycle of type instances.
Definition at line 333 of file TypeSystem.h.
Constructor & Destructor Documentation
TypeEnvironment() [1/2]
souffle::TypeEnvironment::TypeEnvironment ()
Definition at line 54 of file TypeSystem.cpp.
{
     clear();
 }
TypeEnvironment() [2/2]
souffle::TypeEnvironment::TypeEnvironment (const TypeEnvironment &) delete
~TypeEnvironment()
souffle::TypeEnvironment::~TypeEnvironment ()
Definition at line 58 of file TypeSystem.cpp.
References types.
{
     for (const auto& cur : types) {
         delete cur.second;
     }
 }
Member Function Documentation
addType()
void souffle::TypeEnvironment::addType (Type & type) private
Register types created by one of the factory functions.
Definition at line 105 of file TypeSystem.cpp.
References souffle::Type::getName(), souffle::Type::name, and types.
{
     const AstQualifiedName& name = type.getName();
     assert(types.find(name) == types.end() && "Error: registering present type!");
     types[name] = &type;
 }
clear()
void souffle::TypeEnvironment::clear ()
Definition at line 64 of file TypeSystem.cpp.
References types.
{
     // clear list of stored types
     for (const auto& cur : types) {
         delete cur.second;
     }
     types.clear();
     // re-initialize type environment
     createType<PredefinedType>("number");
     createType<PredefinedType>("float");
     createType<PredefinedType>("symbol");
     createType<PredefinedType>("unsigned");
 }
createFloatType()
PrimitiveType& souffle::TypeEnvironment::createFloatType (const AstQualifiedName & name) inline
Definition at line 355 of file TypeSystem.h.
References souffle::Type::name.
{
         return createType<PrimitiveType>(name, getFloatType());
     }
createNumericType()
PrimitiveType& souffle::TypeEnvironment::createNumericType (const AstQualifiedName & name) inline
Definition at line 351 of file TypeSystem.h.
References souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<PrimitiveType>(name, getNumberType());
     }
createRecordType()
RecordType& souffle::TypeEnvironment::createRecordType (const AstQualifiedName & name) inline
Definition at line 371 of file TypeSystem.h.
References souffle::getType(), and souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<RecordType>(name);
     }
createSymbolType()
PrimitiveType& souffle::TypeEnvironment::createSymbolType (const AstQualifiedName & name) inline
Definition at line 363 of file TypeSystem.h.
References souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<PrimitiveType>(name, getSymbolType());
     }
createType()
template<typename T , typename... Args> T& souffle::TypeEnvironment::createType (const AstQualifiedName & name, const Args &... args) inline
Definition at line 345 of file TypeSystem.h.
{
         auto* res = new T(*this, name, args...);
         addType(*res);
         return *res;
     }
createUnionType()
UnionType& souffle::TypeEnvironment::createUnionType (const AstQualifiedName & name) inline
Definition at line 367 of file TypeSystem.h.
References souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<UnionType>(name);
     }
createUnsignedType()
PrimitiveType& souffle::TypeEnvironment::createUnsignedType (const AstQualifiedName & name) inline
Definition at line 359 of file TypeSystem.h.
References souffle::Type::name.
{
         return createType<PrimitiveType>(name, getUnsignedType());
     }
getAllTypes()
TypeSet souffle::TypeEnvironment::getAllTypes () const
Definition at line 97 of file TypeSystem.cpp.
References souffle::TypeSet::insert(), and types.
Referenced by souffle::getLeastCommonSupertypes().
{
     TypeSet res;
     for (const auto& cur : types) {
         res.insert(*cur.second);
     }
     return res;
 }
getFloatType()
const Type& souffle::TypeEnvironment::getFloatType () const inline
Definition at line 391 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::isFloatType().
{
         return getType("float");
     }
getModifiableType()
Type * souffle::TypeEnvironment::getModifiableType (const AstQualifiedName & name)
Definition at line 87 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     auto pos = types.find(name);
     return (pos == types.end()) ? nullptr : pos->second;
 }
getNumberType()
const Type& souffle::TypeEnvironment::getNumberType () const inline
Definition at line 383 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::isNumberType(), and souffle::isSubtypeOf().
{
         return getType("number");
     }
getSymbolType()
const Type& souffle::TypeEnvironment::getSymbolType () const inline
Definition at line 395 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::isSubtypeOf(), and souffle::isSymbolType().
{
         return getType("symbol");
     }
getType()
const Type & souffle::TypeEnvironment::getType (const AstQualifiedName & ident) const
Definition at line 92 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstTranslator::getRecordsTypes(), souffle::AstTranslator::translateDirectives(), souffle::AstTranslator::translateProgram(), and souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     assert(isType(ident));
     return *(types.find(ident)->second);
 }
getUnsignedType()
const Type& souffle::TypeEnvironment::getUnsignedType () const inline
Definition at line 387 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::isUnsignedType().
{
         return getType("unsigned");
     }
isPredefinedType() [1/2]
bool souffle::TypeEnvironment::isPredefinedType (const AstQualifiedName & identifier) const inline
Definition at line 403 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::AstSemanticChecker::checkRecordType(), souffle::AstSemanticChecker::checkRelationDeclaration(), and souffle::AstSemanticChecker::checkUnionType().
{
         if (isType(identifier)) {
             return isPredefinedType(getType(identifier));
         } else {
             return false;
         }
     }
isPredefinedType() [2/2]
bool souffle::TypeEnvironment::isPredefinedType (const Type & typeName) const inline
Definition at line 411 of file TypeSystem.h.
References souffle::Type::name, and souffle::Type::print().
{
         return predefinedTypes().contains(typeName);
     }
isType() [1/2]
bool souffle::TypeEnvironment::isType (const AstQualifiedName & ident) const
Definition at line 78 of file TypeSystem.cpp.
References types.
Referenced by souffle::UnionType::add(), souffle::RecordType::add(), souffle::TypeAnalysis::analyseTypes(), souffle::getGreatestCommonSubtypes(), souffle::getLeastCommonSupertypes(), souffle::isSubtypeOf(), and souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     return types.find(ident) != types.end();
 }
isType() [2/2]
bool souffle::TypeEnvironment::isType (const Type & type) const
Definition at line 82 of file TypeSystem.cpp.
References souffle::Type::getName(), and souffle::getType().
{
     const Type& t = getType(type.getName());
     return t == type;
 }
predefinedTypes()
TypeSet souffle::TypeEnvironment::predefinedTypes () const inline
Definition at line 399 of file TypeSystem.h.
References souffle::getType().
{
         return TypeSet(getType("number"), getType("unsigned"), getType("float"), getType("symbol"));
     }
print()
void souffle::TypeEnvironment::print (std::ostream & out) const
Definition at line 436 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeEnvironmentAnalysis::print().
{
     out << "Types:\n";
     for (const auto& cur : types) {
         out << "\t" << *cur.second << "\n";
     }
 }
swap()
void souffle::TypeEnvironment::swap (TypeEnvironment & env) inline
Definition at line 428 of file TypeSystem.h.
References types, and types.
{
         types.swap(env.types);
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const TypeEnvironment & environment) friend
Definition at line 423 of file TypeSystem.h.
{
         environment.print(out);
         return out;
     }
Field Documentation
types
std::map<AstQualifiedName, Type*> souffle::TypeEnvironment::types private
The list of covered types.
Definition at line 434 of file TypeSystem.h.
Referenced by swap().
The documentation for this class was generated from the following files:
TypeSystem.h
TypeSystem.cpp